apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: java-quarkus-169832932
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/hacdev/2uflbswx-tenant/test-app-169832932/java-quarkus-169832932@sha256:62a032c4e190ef990b1465052bed701933c865524d3c431729d532824860ee84
        name: my-java-quarkus
        resources: {}
status: {}
