apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-169832932
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-169832932
    app.kubernetes.io/part-of: test-app-169832932
  name: java-quarkus-169832932
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-169832932
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-169832932
    spec:
      containers:
      - image: quay.io/hacdev/2uflbswx-tenant/test-app-169832932/java-quarkus-169832932@sha256:62a032c4e190ef990b1465052bed701933c865524d3c431729d532824860ee84
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
